-- MySQL Script generated by MySQL Workbench
-- Tue 13 Feb 2018 12:52:56 PM +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema user_consent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_consent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_consent` DEFAULT CHARACTER SET latin1 ;
USE `user_consent` ;

-- -----------------------------------------------------
-- Table `user_consent`.`DATA_CONTROLLER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`DATA_CONTROLLER` (
  `DATA_CONTROLLER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ORGANIZATION_NAME` VARCHAR(100) NULL DEFAULT NULL,
  `CONTACT_NAME` VARCHAR(100) NULL DEFAULT NULL,
  `STREET` VARCHAR(100) NULL DEFAULT NULL,
  `COUNTRY` CHAR(50) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(254) NULL DEFAULT NULL,
  `PHONE_NUMBER` CHAR(20) NULL DEFAULT NULL,
  `PUBLIC_KEY` VARCHAR(500) NULL DEFAULT NULL,
  `POLICY_URL` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`DATA_CONTROLLER_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`PII_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`PII_CATEGORY` (
  `PII_CAT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PII_CAT` CHAR(30) NULL DEFAULT NULL,
  `PII_CAT_DESCRIPTION` VARCHAR(1000) NULL DEFAULT NULL,
  `SENSITIVITY` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PII_CAT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`THIRD_PARTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`THIRD_PARTY` (
  `THIRD_PARTY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `THIRD_PARTY_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`THIRD_PARTY_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`PURPOSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`PURPOSES` (
  `PURPOSE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PURPOSE` VARCHAR(150) NULL DEFAULT NULL,
  `PRIMARY_PURPOSE` TINYINT(1) NULL DEFAULT NULL,
  `TERMINATION` VARCHAR(200) NULL DEFAULT NULL,
  `THIRD_PARTY_DIS` TINYINT(1) NULL DEFAULT NULL,
  `THIRD_PARTY_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PURPOSE_ID`),
  INDEX `THIRD_PARTY_ID` (`THIRD_PARTY_ID` ASC),
  CONSTRAINT `PURPOSES_ibfk_2`
    FOREIGN KEY (`THIRD_PARTY_ID`)
    REFERENCES `user_consent`.`THIRD_PARTY` (`THIRD_PARTY_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`PURPOSE_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`PURPOSE_CATEGORY` (
  `PURPOSE_CAT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PURPOSE_CAT_SHORT_CODE` CHAR(50) NULL DEFAULT NULL,
  `PURPOSE_CAT_DESCRIPTION` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`PURPOSE_CAT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`PURPOSE_MAP_PII_CAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`PURPOSE_MAP_PII_CAT` (
  `PURPOSE_ID` INT(11) NOT NULL,
  `PII_CAT_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PURPOSE_ID`, `PII_CAT_ID`),
  INDEX `PURPOSE_MAP_PII_CAT_ibfk_2` (`PII_CAT_ID` ASC),
  CONSTRAINT `PURPOSE_MAP_PII_CAT_ibfk_1`
    FOREIGN KEY (`PURPOSE_ID`)
    REFERENCES `user_consent`.`PURPOSES` (`PURPOSE_ID`),
  CONSTRAINT `PURPOSE_MAP_PII_CAT_ibfk_2`
    FOREIGN KEY (`PII_CAT_ID`)
    REFERENCES `user_consent`.`PII_CATEGORY` (`PII_CAT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`PURPOSE_MAP_PURPOSE_CAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`PURPOSE_MAP_PURPOSE_CAT` (
  `PURPOSE_ID` INT(11) NULL DEFAULT NULL,
  `PURPOSE_CAT_ID` INT(11) NULL DEFAULT NULL,
  INDEX `PURPOSE_ID` (`PURPOSE_ID` ASC),
  INDEX `PURPOSE_CAT_ID` (`PURPOSE_CAT_ID` ASC),
  CONSTRAINT `PURPOSE_MAP_PURPOSE_CAT_ibfk_1`
    FOREIGN KEY (`PURPOSE_ID`)
    REFERENCES `user_consent`.`PURPOSES` (`PURPOSE_ID`),
  CONSTRAINT `PURPOSE_MAP_PURPOSE_CAT_ibfk_2`
    FOREIGN KEY (`PURPOSE_CAT_ID`)
    REFERENCES `user_consent`.`PURPOSE_CATEGORY` (`PURPOSE_CAT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`PURPOSE_MAP_THIRD_PARTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`PURPOSE_MAP_THIRD_PARTY` (
  `PURPOSE_ID` CHAR(10) NULL DEFAULT NULL,
  `THIRD_PARTY_ID` INT(11) NULL DEFAULT NULL,
  INDEX `PURPOSE_ID` (`PURPOSE_ID` ASC),
  INDEX `PURPOSE_MAP_THIRD_PARTY_ibfk_2` (`THIRD_PARTY_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`RECEIVED_CR_TRACKER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`RECEIVED_CR_TRACKER` (
  `RECEIPT_ID` VARCHAR(100) NULL DEFAULT NULL,
  `RECEIPT_JWT` BLOB NULL DEFAULT NULL,
  `RECEIVED_TIMESTAMP` DATETIME NULL DEFAULT NULL,
  `STATUS` CHAR(20) NULL DEFAULT NULL,
  `JURISDICTION` CHAR(10) NULL DEFAULT NULL,
  `VERSION` CHAR(15) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`SERVICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`SERVICES` (
  `SERVICE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SERVICE_DESCRIPTION` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICE_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`TRANSACTION_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`TRANSACTION_DETAILS` (
  `COLLECTION_METHOD` VARCHAR(100) NULL DEFAULT NULL,
  `SGUID` VARCHAR(100) NOT NULL,
  `PII_PRINCIPAL_ID` VARCHAR(100) NULL DEFAULT NULL,
  `DATA_CONTROLLER_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SGUID`),
  INDEX `TRANSACTION_DETAILS_ibfk_1` (`DATA_CONTROLLER_ID` ASC),
  CONSTRAINT `TRANSACTION_DETAILS_ibfk_1`
    FOREIGN KEY (`DATA_CONTROLLER_ID`)
    REFERENCES `user_consent`.`DATA_CONTROLLER` (`DATA_CONTROLLER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`SERVICE_MAP_CRID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`SERVICE_MAP_CRID` (
  `SGUID` VARCHAR(100) NOT NULL,
  `SERVICE_ID` INT(11) NOT NULL,
  `PURPOSE_ID` INT(11) NOT NULL,
  `CONSENT_TYPE` CHAR(20) NULL DEFAULT NULL,
  `EXACT_TERMINATION` VARCHAR(30) NULL DEFAULT NULL,
  `CONSENT_TIME` VARCHAR(100) NULL DEFAULT NULL,
  `COLLECTION_METHOD` VARCHAR(50) NULL DEFAULT NULL,
  `STATUS` CHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`SGUID`, `SERVICE_ID`, `PURPOSE_ID`),
  INDEX `SERVICE_MAP_CRID_ibfk_2` (`SERVICE_ID` ASC),
  INDEX `SERVICE_MAP_CRID_ibfk_3` (`PURPOSE_ID` ASC),
  CONSTRAINT `SERVICE_MAP_CRID_ibfk_1`
    FOREIGN KEY (`SGUID`)
    REFERENCES `user_consent`.`TRANSACTION_DETAILS` (`SGUID`),
  CONSTRAINT `SERVICE_MAP_CRID_ibfk_2`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `user_consent`.`SERVICES` (`SERVICE_ID`),
  CONSTRAINT `SERVICE_MAP_CRID_ibfk_3`
    FOREIGN KEY (`PURPOSE_ID`)
    REFERENCES `user_consent`.`PURPOSES` (`PURPOSE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_consent`.`SERVICE_MAP_PURPOSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_consent`.`SERVICE_MAP_PURPOSE` (
  `SERVICE_ID` INT(11) NOT NULL,
  `PURPOSE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SERVICE_ID`, `PURPOSE_ID`),
  INDEX `SERVICE_MAP_PURPOSE_ibfk_1` (`PURPOSE_ID` ASC),
  CONSTRAINT `SERVICE_MAP_PURPOSE_ibfk_1`
    FOREIGN KEY (`PURPOSE_ID`)
    REFERENCES `user_consent`.`PURPOSES` (`PURPOSE_ID`),
  CONSTRAINT `SERVICE_MAP_PURPOSE_ibfk_2`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `user_consent`.`SERVICES` (`SERVICE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

